name: Add latest tag to new release
on:
  release:
    types: [published]

jobs:
  run:
    name: Run local action
    runs-on: ubuntu-latest
    steps:
      - name: Actions Tagger
        uses: Actions-R-Us/actions-tagger@v2.0.2
        with:
          publish_latest_tag: true
