name: Add latest tag to new release
on:
  release:
    types: [published]

jobs:
  run:
    name: Run local action
    runs-on: ubuntu-latest
    steps:
      - name: Run latest-tag
        uses: thevanguardian/latest-tag@v2.0.0
        with:
          # You can change the name of the tag with this input.
          # Default: 'latest'
          tag-name: latest
